name: send email

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Email_PWD: ${{ secrets.Email_PWD }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Check setuptools version
        run: |
            pip show setuptools
      - name: Install or downgrade setuptools
        run: |
            pip install setuptools==57.5.0
      - name: Install dependencies
        run: |          
          pip install -r requirements.txt
      - name: Send Email
        run: |
          python -u  src/SendEmail.py
          
