name: send email

on:
  schedule:
    - cron: "0 7 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Email_PWD: ${{ secrets.Email_PWD }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Send Email
        run: |
          python -u  src/SendEmail.py
          
